name: Deploy Poll Master

on:
  push:
    branches: [ "main" ] # Runs every time you push to main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing_db
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, curl, libxml, mysql
        coverage: xdebug

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Copy .env
      run: cp .env.example .env

    - name: Generate Key
      run: php artisan key:generate

    - name: Compile Assets (Tailwind/JS)
      run: |
        npm install
        npm run build

    - name: Run Migrations and Seeders
      run: php artisan migrate --seed

    - name: Run Tests
      run: php artisan test